# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lucas2dev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonz-ai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  overview:
    handler: functions/overview/index.handler
    events:
      - httpApi:
          path: /overview
          method: get

  booking:
    handler: functions/booking/index.handler
    events:
      - httpApi:
          path: /booking
          method: post

  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: /deleteBooking/{id}
          method: post

  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /updateBooking/{id}
          method: put

# Define the resources that this project will use. In this case, a DynamoDB table.
resources:
  Resources:
    BookingsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: rooms
            AttributeType: L
          - AttributeName: status
            AttributeType: S
          - AttributeName: price
            AttributeType: N
          - AttributeName: amount_of_rooms
            AttributeType: N
          - AttributeName: amount_of_guests
            AttributeType: N
          - AttributeName: check_in
            AttributeType: S
          - AttributeName: check_out
            AttributeType: S
          - AttributeName: guest_name
            AttributeType: S
          - AttributeName: guest_email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: HASH
          - AttributeName: rooms
            KeyType: HASH
          - AttributeName: status
            KeyType: HASH
          - AttributeName: price
            KeyType: HASH
          - AttributeName: amount_of_rooms
            KeyType: HASH
          - AttributeName: amount_of_guests
            KeyType: HASH
          - AttributeName: check_in
            KeyType: HASH
          - AttributeName: check_out
            KeyType: HASH
          - AttributeName: guest_name
            KeyType: HASH
          - AttributeName: guest_email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    RoomsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: price
            AttributeType: N
          - AttributeName: amount_of_people
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: HASH
          - AttributeName: type
            KeyType: HASH
          - AttributeName: price
            KeyType: HASH
          - AttributeName: amount_of_people
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
